version: "3"

services:
  strapi:
    build: .
    container_name: svelte-boom-strapi
    env_file:
      - .env.production       # or remove this if you’ll set env vars in Coolify
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: svelte-boom-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
