version: "3"

services:
  strapi:
    build: .
    container_name: svelte-boom-strapi
    ports:
      - "1337:1337"
    depends_on:
      - db
    volumes:
      - strapi-uploads:/app/public/uploads
volumes:
  pgdata:
  strapi-uploads:
